server:
  port: 8000
spring:
  application:
    name: example
  datasource:
    ###Sql-Server
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1;encrypt=false;DatabaseName=flowlong
    username: sa
    password: 密码

    ###My-Sql
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://地址:3306/flowlong?characterEncoding=utf8&useSSL=false
#    username: root
#    password: 密码


# FlowLong Config
flowlong:
  remind:
    cron: "*/5 * * * * ?"
  eventing:
    task: true

